# ===== Serveur =====
server.port=8080

# ===== Base de donnees MySQL (XAMPP) =====
spring.datasource.url=jdbc:mysql://localhost:3306/devis_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ===== JPA / Hibernate (Code First : tables generees automatiquement) =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== JWT =====
# Cle secrete pour signer les tokens (a changer en production)
app.jwt.secret=ZXN0YXRtYXItZGV2aXMtc2VjcmV0LWtleS1wb3VyLWp3dC0yMDI2LXRyZXMtbG9uZ3VlLWNsZQ==
# Duree de validite du token : 24 heures (en millisecondes)
app.jwt.expiration=86400000

# ===== Swagger =====
springdoc.swagger-ui.path=/swagger-ui.html